name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install nativescript
      run: |
      npm i -g nativescript@latest
      npm i tns-core-modules@latest
    - name: npm i and lint
      run: |
        npm i
        npm run tslint
      env:
        CI: true
