name: NativeScript Build Android Latest

on: [push]

jobs:
  build-latest:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm Install & Install Angular CLI
      run: |
        npm i
        npm install @angular/cli
    - name: Update & Upgrade
      run: |
        npm i nativescript@latest
        npm i tns-core-modules@latest
        .\tns update
        .\tns platform clean android
    - name: TNS Infos
      run: .\tns info
    - name: Build Android
      run: .\tns build Android
