name: NativeScript Info

on: [push]

jobs:
  info:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Npm Install
      run: npm i
    - name: TNS Infos
      run: .\tns info
      # ToDo if text condains "Update", do Fail (exit 1)