name: Nativescript TSLint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Nativescript CLI
      run: npm install nativescript@latest
    - name: GET NS Version
      run: |
      echo Using following Nativescript Version
      .\tns --version
    - name: Install Angular CLI
      run: npm install @angular/cli
    - name: npm i and lint
      run: |
        npm i
        npm run lint
      env:
        CI: true
