name: NativeScript TSLint & doctor

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm Install
      run: |
        npm i
    - name: NativeScript Version
      run: .\tns --version
      shell: cmd
    - name: NativeScript Repo Dependencies Infos
      run: .\tns info
    - name: NativeScript Doctor
      run: .\tns Doctor
    - name: Install Angular CLI
      run: npm install @angular/cli
    - name: npm i and lint
      run: |
        npm i
        npm run lint
      env:
        CI: true
