name: NativeScript TSLint

on: [push]

jobs:
  build:

    runs-on: windows-latest
    # node-version: 12.x

    steps:
    - uses: actions/checkout@v1
    # - name: Use Node.js ${{ node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ node-version }}
    - name: npm Install
      run: |
        npm i
    - name: Install Angular CLI
      run: npm install @angular/cli
    - name: tslint
      run: npm run lint
      env:
        CI: true
