name: NativeScript TSLint

on: [push]

jobs:
  tslint:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: npm Install
      run: |
        npm i
    - name: Install Angular CLI
      run: npm install @angular/cli
    - name: tslint
      run: npm run lint
