name: NativeScript TSLint & doctor

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install NativeScript CLI
      run: npm install nativescript@latest
    - name: NativeScript Version
      run: .\tns --version
    - name: NativeScript Repo Dependencies Infos
      run: .\tns info
    - name: NativeScript Doctor
      run: .\tns Doctor
    - name: Install Angular CLI
      run: npm install @angular/cli
    - name: npm i and lint
      run: |
        npm i
        npm run lint
      env:
        CI: true
