name: Nativescript TSLint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install nativescript
      run: npm i nativescript tns-core-modules
    - name: npm i and lint
      run: |
        npm i
        npm run tslint
      env:
        CI: true
