name: Nativescript TSLint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Nativescript CLI
      run: npm install -g nativescript@latest
    - name: TNS Version
      run: tns --version
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: npm i and lint
      run: |
        npm i
        npm run tslint
      env:
        CI: true
